### PR TITLE
Fix #466 projex generates pyproject.toml

### LINKED ISSUE #386: 20240131 Update readthedocs generation
Precipitated by [this notification](https://blog.readthedocs.com/drop-support-system-packages/). Investigate how they currently generate this documentation vs the new method and make changes accordingly.

See also radiasoft/pykern#37

- [x] radiasoft/pykern#429
- [x] radiasoft/pykern#393
- [x] https://github.com/radiasoft/download/issues/526
- [ ] radiasoft/devsecops#521

To clarify a bit, here's what readthedocs is expecting in the repo of interest:
- .readthedocs.yml at the root level, minimally:
```yml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_build:
     - <commands to run>

sphinx:
  configuration: docs/conf.py

python:
    install:
    - requirements: docs/requirements.txt
```
- docs/conf.py
- docs/requirements.txt

In the current state of PR radiasoft/pykern#392, "commands to run" is `python setup.py install --force` (which readthedocs used to do automatically). That's done to run pksetup, which generates the conf.py above; accordingly, requirements.txt contains pykern. The purpose of radiasoft/pykern#393 is to take pksetup out of the process and the purpose of https://github.com/radiasoft/download/issues/526 is to make "commands to run" something like `curl https://radia.run | bash -s readthedocs`

### LINKED ISSUE #393: Extract readthedocs content from pksetup to a pkcli
Now that readthedocs no longer automatically runs setup.py, we can move the `_sphinx_apidoc` functionality into its own pkcli module. We will also create an installer in [downloads](https://github.com/radiasoft/download) for readthedocs to run to generate the required `conf.py`.

### LINKED ISSUE #429: Make readthedocs conform to current build process
Breaking this out of #386 since it's fairly simple and the other sub-tasks will start from that point

### LINKED ISSUE #449: node.js github actions are deprecated
> Node.js 16 actions are deprecated. Please update the following actions
> to use Node.js 20: actions/checkout@v3. For more information see:
> https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

### LINKED ISSUE #466: Switch projex to pyproject.toml
- LICENSE should be force selected from command line
- Look at proprietary example
- Remove tox and readthedocs

### PR DESCRIPTION
**Pull request by robnagler**
- pksetup: removed tox, readthedocs support Fix #429 added readthedocs.yml
Fix #386 projex generates proper sphinx and readthedocs.yml Fix #393 added pkcli.sphinx.prepare for readthedocs
- Added sphinx test which also tests projex
- Fixed various RST errors in modules Fix #449 use GitHub workflow actions/checkout@v4 (also projex)

### CODE REVIEW

**Review by rorour — CHANGES_REQUESTED** [review]
`g tox` still shows some instances that I think can be removed.

**Comment by rorour** [comment]
I'm getting [this error](https://github.com/radiasoft/pykern/issues/462#issuecomment-2023864462). Is projex broken?

**Comment by rorour** [comment]
Actually not exactly that error, but it seems related.

```
[py3;@v wxyz]$ pykern projex init_rs_tree "my wxyz project"
Traceback (most recent call last):
  File "/home/vagrant/.pyenv/versions/py3/bin/pykern", line 8, in <module>
    sys.exit(main())
  File "/home/vagrant/src/radiasoft/pykern/pykern/pykern_console.py", line 17, in main
    return pkcli.main("pykern")
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/__init__.py", line 166, in main
    res = argh.dispatch(parser, argv=argv)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/argh/dispatching.py", line 183, in dispatch
    for line in lines:
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/argh/dispatching.py", line 294, in _execute_command
    for line in result:
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/argh/dispatching.py", line 277, in _call
    result = function(*positional, **keywords)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/projex.py", line 76, in init_rs_tree
    init_tree(
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkcli/projex.py", line 108, in init_tree
    base = pkresource.filename("projex")
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkresource.py", line 47, in filename
    for f, p in _files(relative_filename, caller_context, packages):
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkresource.py", line 90, in _files
    pkg_resources.resource_filename(
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1181, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 391, in get_provider
    return _find_adapter(_provider_factories, loader)(module)
  File "/home/vagrant/.pyenv/versions/3.9.15/envs/py3/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1460, in __init__
    self.module_path = os.path.dirname(getattr(module, '__file__', ''))
  File "/home/vagrant/.pyenv/versions/3.9.15/lib/python3.9/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by robnagler** [comment]
@rorour I can't reproduce the projex failure [above](https://github.com/radiasoft/pykern/pull/488#issuecomment-2187586541):

```sh
$ mkdir wxyz; cd wxyz; git init .; pykern projex init_rs_tree "my wxyz project"
Initialized empty Git repository in /home/vagrant/src/radiasoft/wxyz/.git/
$
```

**Comment by robnagler** [comment]
> g tox still shows some instances that I think can be removed.

[11e648a](https://github.com/radiasoft/pykern/pull/488/commits/11e648afc487cf328ed8504d6291cef4ceff949b)

**Review by rorour — APPROVED** [review]
It works in my vm_devbox but not my local vm. I tried radia_run sirepo-dev and uninstalled/reinstalled pykern. I don't have any idea what's causing the failure.

**Comment by robnagler** [comment]
It's probably an old python package on your local vm.

**Comment by rorour** [comment]
Do you know how I can find out which package and/or how to fix it?

**Comment by moellep** [comment]
You could run "pip list --outdated" to see old packages and update them using a command found here: 
https://stackoverflow.com/questions/2720014/how-to-upgrade-all-python-packages-with-pip

Probably need to run "pip install -e ." in the sirepo and pykern directory afterward to downgrade anything. 

Maybe @robnagler has a better way to do this.

**Comment by robnagler** [comment]
Try this first:

```sh
cd ~/src/radiasoft/pykern
pip install --upgrade --upgrade-strategy only-if-needed .
```

If projex still fails, we have something that needs bumping in pyproject.toml. Then we would want to know which packages need updating and that's trickier to debug, because you have to upgrade packages one at a time.

**Comment by rorour** [comment]
> cd ~/src/radiasoft/pykern
> pip install --upgrade --upgrade-strategy only-if-needed .

This fixed it. Thanks

**Pull request merged**
