### PR TITLE
Encode integral types fail otherwise

### LINKED ISSUE #63: Encode numpy.int64 in py3
Reported by @moellep:
Here's a script which produces different output under py2 or py3:

>>
import numpy as np
import pykern.pkjson

x = np.array([1, 2, 3])
r = [min(x), max(x)]

print(pykern.pkjson.dump_pretty(r))
<<

in py2, the output is [1, 3]
in py3, the output is ["1", "3"]

I think this is because we have a custom Encoder in pkjson. Could the Encoder be extended to know about numpy types, or have the Encoder crash if it finds a non int/float/str type?

### PR DESCRIPTION
**Pull request by e-carlin**
Fix #63.

### CODE REVIEW

**Comment by e-carlin** [comment]
Not ready to merge. Running jspec dc cooling example yields:
```../sirepo/http_reply.py:243:_gen_exception_error unsupported exception=<type 'exceptions.TypeError'> msg=Unable to encode obj=/home/vagrant/src/radiasoft/sirepo/run/user/Jm9NBzeE/jspec/lib of type=<class 'py._path.local.LocalPath'>```

**Comment by e-carlin** [comment]
Fixed py_path

**Comment by robnagler** [comment]
what's the status of this?

**Comment by e-carlin** [comment]
> what's the status of this?
It works so far in my testing except for the case below.

I get this error when running the sbatch tests.
```
Traceback (most recent call last):
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 222, in receive
    )(req)
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 556, in _receive_api_runSimulation
    error=e,
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 323, in __db_update
    return self.__db_write()
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/job_supervisor.py", line 326, in __db_write
    sirepo.util.json_dump(self.db, path=self.__db_file(self.db.computeJid))
  File "/home/vagrant/src/radiasoft/sirepo/sirepo/util.py", line 176, in json_dump
    res = pykern.pkjson.dump_pretty(obj, pretty=pretty, allow_nan=False, **kwargs)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkjson.py", line 43, in dump_pretty
    res = json.dumps(obj, separators=(',', ':'), cls=Encoder, **kwargs)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/vagrant/.pyenv/versions/3.7.2/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/vagrant/src/radiasoft/pykern/pykern/pkjson.py", line 22, in default
    raise TypeError('Unable to encode obj={} of type={}'.format(obj, type(obj)))
TypeError: Unable to encode obj=SRException(params={'isModal': True, 'reason': 'no-creds', 'simulationId': 'rzWRbEhl', 'simulationType': 'warppba', 'report': 'animation', 'host': 'v.radia.run'},routeName=sbatchLogin) of type=<class 'sirepo.util\
.SRException'>
```
It can't encode the SRException which is raised when sbatch creds are invalid or not present. Any thoughts on how to resolve?

**Comment by robnagler** [comment]
@e-carlin what should we do about this? I don't think we need it(?).

**Comment by e-carlin** [comment]
I agree - not needed.

**Pull request closed without merging**
