### PR TITLE
Fix #268: ignore lines

### LINKED ISSUE #268: case_dirs/file_eq needs to take ingore lines as input
case_dirs and file_eq need to be able to take a list of lines to be ignored for file comparison

### PR DESCRIPTION
**Pull request by gurhar1133**
Ignore lines added to file_eq/case_dirs
Multiple regexes can be passed through to be ignored
The test failures (projex and setup) fail on master.

### CODE REVIEW

**Comment by mkeilman** [comment]
I think there should be a test added to pkunit_test for this

**Review by mkeilman — COMMENTED** [review]
This all looks fine, though per my other comment it could use a test

**Comment by robnagler** [comment]
@gurhar1133 does the checklist show up when you open a PR? One of the Qs is "test required"?

**Comment by gurhar1133** [comment]
> @gurhar1133 does the checklist show up when you open a PR? One of the Qs is "test required"?

yes, but I didn't understand if that was asking me if I think tests are required or if I want to ask reviewers if I think tests are required

**Comment by robnagler** [comment]
That's a good point. I have been taking it from the author's perspective. Perhaps we want it from the reviewer's perspective. I'll set something up in discuss. In any event, please add a test. :)

**Pull request closed without merging**
